### ISSUE TITLE
Broken link in Cache Expiry help item

### ISSUE THREAD

**Issue by m-bodmer** [passmarked/network#28]
The following URL http://heatherevens.me.uk/2013/07/01/filename-based-cache-busting-made-easy/ results in a 404.

It is located here:
https://github.com/passmarked/network/blame/develop/docs/expire.internal.md#L9

**Comment by Johanndutoit** [comment]
Ah awesome, thanks for noting. Will replace with a new source

**Comment by Johanndutoit** [comment]
PR is over at - https://github.com/passmarked/network/pull/29. Will merge after tests pass and will be live on the site in a few hours, depending on cache. 

Replaced both links with some that I think make a bit more sense in the context.

**Comment by Johanndutoit** [comment]
Merged, and as mentioned will be live in a few hours. And will be included in the next NPM release version. Quickly did it to avoid any 404's on the site, but any other resources feel free to open a PR and add to the list :)
